/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package ui;
import java.security.NoSuchAlgorithmException;
import java.util.HashMap;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import model.Encryptor;
import model.Professor;
import model.Student;
import model.StudentRecord;
import ui.Student_JPanel;
import ui.Professor_JPanel;
import ui.EmployeeJPanel;
import model.Course;
import model.CourseHistory;
import model.ProfessorDirectory;
import model.Student;
import model.StudentCourse;
import model.StudentRecord;
import model.Transcript;


/**
 *
 * @author 91961
 */
public class MainJFrame extends javax.swing.JFrame {

    /**
     * Creates new form MainJFrame
     */
    StudentRecord stdrecord;
    ProfessorDirectory profrecord;
    CourseHistory coursedetails;
    StudentCourse studentregisterdetails;
    private Course course;
    StudentRecord studentRecord;
    Student_JPanel studentpanel;
    AdminJPanel adminPanel;
    Professor_JPanel profpanel;
    EmployeeJPanel empPanel;
    CourseHistory courseSpringdetails;
    Transcript transcript;
    Transcript gettranscript;
    StudentCourse studentSpringdetails;
    Professor professor;
         


    HashMap<String, String> database = new HashMap<String, String>();

    public MainJFrame() {
        initComponents();
        this.stdrecord= new StudentRecord();
        this.profrecord= new ProfessorDirectory();
        this.transcript = new Transcript();
        this.professor = new Professor();
        this.coursedetails = new CourseHistory();
        this.courseSpringdetails = new CourseHistory();
        transcript = new Transcript();
        gettranscript = new Transcript();

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        btnstduent = new javax.swing.JButton();
        btnprof = new javax.swing.JButton();
        btnadmin = new javax.swing.JButton();
        btnemp = new javax.swing.JButton();
        jPanel2 = new javax.swing.JPanel();
        EmptyPanel = new javax.swing.JPanel();
        StudentReg = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        btnregstd = new javax.swing.JButton();
        txtstdid = new javax.swing.JTextField();
        txtstdname = new javax.swing.JTextField();
        txtstdaddr = new javax.swing.JTextField();
        txtstdphone = new javax.swing.JTextField();
        txtstdemail = new javax.swing.JTextField();
        txtstdusername = new javax.swing.JTextField();
        txtstdpass = new javax.swing.JPasswordField();
        ProfessorLog = new javax.swing.JPanel();
        jLabel13 = new javax.swing.JLabel();
        btnproflogin = new javax.swing.JButton();
        jLabel9 = new javax.swing.JLabel();
        txtprofusername = new javax.swing.JTextField();
        txtprofpass = new javax.swing.JPasswordField();
        jLabel10 = new javax.swing.JLabel();
        Stdlogreg = new javax.swing.JPanel();
        btnStdlogin = new javax.swing.JButton();
        btnStdregister = new javax.swing.JButton();
        jLabel18 = new javax.swing.JLabel();
        ProfessorReg = new javax.swing.JPanel();
        jLabel15 = new javax.swing.JLabel();
        jLabel16 = new javax.swing.JLabel();
        txtsprofessorid = new javax.swing.JTextField();
        jLabel17 = new javax.swing.JLabel();
        btnsprofessorreg = new javax.swing.JButton();
        jLabel20 = new javax.swing.JLabel();
        txtsprofessorusername = new javax.swing.JTextField();
        jLabel21 = new javax.swing.JLabel();
        txtsprofessorname = new javax.swing.JTextField();
        txtsprofessorpass = new javax.swing.JPasswordField();
        jLabel22 = new javax.swing.JLabel();
        txtsprofessorphone = new javax.swing.JTextField();
        jLabel23 = new javax.swing.JLabel();
        txtsprofessoremail = new javax.swing.JTextField();
        Studentlogin = new javax.swing.JPanel();
        jLabel14 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        txtstudentusername = new javax.swing.JTextField();
        jLabel12 = new javax.swing.JLabel();
        txtstudentpass = new javax.swing.JPasswordField();
        btnstudentlogin = new javax.swing.JButton();
        Proflogreg = new javax.swing.JPanel();
        btnProflogin = new javax.swing.JButton();
        btnProfregister = new javax.swing.JButton();
        jLabel19 = new javax.swing.JLabel();
        Admindasborad = new javax.swing.JPanel();
        jLabel24 = new javax.swing.JLabel();
        btncreateProf = new javax.swing.JButton();
        btncreateStd = new javax.swing.JButton();
        btncreateEmp = new javax.swing.JButton();
        btnviewProf = new javax.swing.JButton();
        btnviewStd = new javax.swing.JButton();
        btncviewEmp = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        btnstduent.setText("Student");
        btnstduent.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnstduentActionPerformed(evt);
            }
        });

        btnprof.setText("Professor");
        btnprof.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnprofActionPerformed(evt);
            }
        });

        btnadmin.setText("Admin");
        btnadmin.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnadminActionPerformed(evt);
            }
        });

        btnemp.setText("Employer");
        btnemp.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnempActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(btnprof, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(btnstduent, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(btnadmin, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                    .addComponent(btnemp, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(73, 73, 73)
                .addComponent(btnstduent)
                .addGap(18, 18, 18)
                .addComponent(btnprof)
                .addGap(18, 18, 18)
                .addComponent(btnadmin)
                .addGap(18, 18, 18)
                .addComponent(btnemp)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jPanel2.setLayout(new java.awt.CardLayout());

        javax.swing.GroupLayout EmptyPanelLayout = new javax.swing.GroupLayout(EmptyPanel);
        EmptyPanel.setLayout(EmptyPanelLayout);
        EmptyPanelLayout.setHorizontalGroup(
            EmptyPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 792, Short.MAX_VALUE)
        );
        EmptyPanelLayout.setVerticalGroup(
            EmptyPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 384, Short.MAX_VALUE)
        );

        jPanel2.add(EmptyPanel, "card4");

        jLabel1.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("Student");
        jLabel1.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);

        jLabel2.setText("STD_ID");

        jLabel3.setText("NAME");

        jLabel4.setText("ADDRESS");

        jLabel5.setText("PHONE NO");

        jLabel6.setText("EMAIL");

        jLabel7.setText("USERNAME");

        jLabel8.setText("PASSWORD");

        btnregstd.setText("Register");
        btnregstd.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnregstdActionPerformed(evt);
            }
        });

        txtstdusername.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtstdusernameActionPerformed(evt);
            }
        });

        txtstdpass.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtstdpassActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout StudentRegLayout = new javax.swing.GroupLayout(StudentReg);
        StudentReg.setLayout(StudentRegLayout);
        StudentRegLayout.setHorizontalGroup(
            StudentRegLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(StudentRegLayout.createSequentialGroup()
                .addGroup(StudentRegLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(StudentRegLayout.createSequentialGroup()
                        .addGap(158, 158, 158)
                        .addGroup(StudentRegLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel7)
                            .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 140, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 140, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 62, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(StudentRegLayout.createSequentialGroup()
                                .addGroup(StudentRegLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(StudentRegLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                        .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 140, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 140, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addComponent(jLabel8, javax.swing.GroupLayout.PREFERRED_SIZE, 140, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(98, 98, 98)
                                .addGroup(StudentRegLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(txtstdname, javax.swing.GroupLayout.DEFAULT_SIZE, 100, Short.MAX_VALUE)
                                    .addComponent(txtstdid, javax.swing.GroupLayout.DEFAULT_SIZE, 100, Short.MAX_VALUE)
                                    .addComponent(txtstdaddr, javax.swing.GroupLayout.DEFAULT_SIZE, 100, Short.MAX_VALUE)
                                    .addComponent(txtstdphone, javax.swing.GroupLayout.DEFAULT_SIZE, 100, Short.MAX_VALUE)
                                    .addComponent(txtstdemail, javax.swing.GroupLayout.DEFAULT_SIZE, 100, Short.MAX_VALUE)
                                    .addComponent(txtstdusername, javax.swing.GroupLayout.DEFAULT_SIZE, 100, Short.MAX_VALUE)
                                    .addComponent(txtstdpass)))))
                    .addGroup(StudentRegLayout.createSequentialGroup()
                        .addGap(296, 296, 296)
                        .addComponent(btnregstd)))
                .addContainerGap(296, Short.MAX_VALUE))
            .addGroup(StudentRegLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(StudentRegLayout.createSequentialGroup()
                    .addGap(174, 174, 174)
                    .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 324, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addContainerGap(294, Short.MAX_VALUE)))
        );
        StudentRegLayout.setVerticalGroup(
            StudentRegLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, StudentRegLayout.createSequentialGroup()
                .addGap(57, 57, 57)
                .addGroup(StudentRegLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtstdid, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(StudentRegLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(txtstdname, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(StudentRegLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(txtstdaddr, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(StudentRegLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5)
                    .addComponent(txtstdphone, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(StudentRegLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel6)
                    .addComponent(txtstdemail, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(StudentRegLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel7)
                    .addComponent(txtstdusername, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(StudentRegLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel8)
                    .addComponent(txtstdpass, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(btnregstd)
                .addContainerGap(60, Short.MAX_VALUE))
            .addGroup(StudentRegLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(StudentRegLayout.createSequentialGroup()
                    .addGap(10, 10, 10)
                    .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addContainerGap(339, Short.MAX_VALUE)))
        );

        jPanel2.add(StudentReg, "card3");

        jLabel13.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel13.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel13.setText("Professor");
        jLabel13.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);

        btnproflogin.setText("Login");
        btnproflogin.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnprofloginActionPerformed(evt);
            }
        });

        jLabel9.setText("USERNAME");

        jLabel10.setText("PASSWORD");

        javax.swing.GroupLayout ProfessorLogLayout = new javax.swing.GroupLayout(ProfessorLog);
        ProfessorLog.setLayout(ProfessorLogLayout);
        ProfessorLogLayout.setHorizontalGroup(
            ProfessorLogLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(ProfessorLogLayout.createSequentialGroup()
                .addGroup(ProfessorLogLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(ProfessorLogLayout.createSequentialGroup()
                        .addGap(174, 174, 174)
                        .addGroup(ProfessorLogLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel9)
                            .addGroup(ProfessorLogLayout.createSequentialGroup()
                                .addComponent(jLabel10, javax.swing.GroupLayout.PREFERRED_SIZE, 140, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(98, 98, 98)
                                .addGroup(ProfessorLogLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(txtprofusername)
                                    .addComponent(txtprofpass, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addComponent(jLabel13, javax.swing.GroupLayout.PREFERRED_SIZE, 324, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(ProfessorLogLayout.createSequentialGroup()
                        .addGap(302, 302, 302)
                        .addComponent(btnproflogin)))
                .addContainerGap(280, Short.MAX_VALUE))
        );
        ProfessorLogLayout.setVerticalGroup(
            ProfessorLogLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(ProfessorLogLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel13, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(96, 96, 96)
                .addGroup(ProfessorLogLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel9)
                    .addComponent(txtprofusername, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(ProfessorLogLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel10)
                    .addComponent(txtprofpass, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(btnproflogin)
                .addContainerGap(150, Short.MAX_VALUE))
        );

        jPanel2.add(ProfessorLog, "card2");

        btnStdlogin.setText("Login");
        btnStdlogin.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnStdloginActionPerformed(evt);
            }
        });

        btnStdregister.setText("Register");
        btnStdregister.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnStdregisterActionPerformed(evt);
            }
        });

        jLabel18.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel18.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel18.setText("Student");
        jLabel18.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);

        javax.swing.GroupLayout StdlogregLayout = new javax.swing.GroupLayout(Stdlogreg);
        Stdlogreg.setLayout(StdlogregLayout);
        StdlogregLayout.setHorizontalGroup(
            StdlogregLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(StdlogregLayout.createSequentialGroup()
                .addGroup(StdlogregLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(StdlogregLayout.createSequentialGroup()
                        .addGap(302, 302, 302)
                        .addComponent(btnStdlogin)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btnStdregister))
                    .addGroup(StdlogregLayout.createSequentialGroup()
                        .addGap(219, 219, 219)
                        .addComponent(jLabel18, javax.swing.GroupLayout.PREFERRED_SIZE, 324, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(249, Short.MAX_VALUE))
        );
        StdlogregLayout.setVerticalGroup(
            StdlogregLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(StdlogregLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel18, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(129, 129, 129)
                .addGroup(StdlogregLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnStdlogin)
                    .addComponent(btnStdregister))
                .addContainerGap(191, Short.MAX_VALUE))
        );

        jPanel2.add(Stdlogreg, "card5");

        jLabel15.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel15.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel15.setText("Professor Registration");
        jLabel15.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);

        jLabel16.setText("PROF_ID");

        jLabel17.setText("PROF_NAME");

        btnsprofessorreg.setText("Register");
        btnsprofessorreg.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnsprofessorregActionPerformed(evt);
            }
        });

        jLabel20.setText("USERNAME");

        jLabel21.setText("PASSWORD");

        jLabel22.setText("PROF_PHONE");

        jLabel23.setText("PROF_EMAIL");

        javax.swing.GroupLayout ProfessorRegLayout = new javax.swing.GroupLayout(ProfessorReg);
        ProfessorReg.setLayout(ProfessorRegLayout);
        ProfessorRegLayout.setHorizontalGroup(
            ProfessorRegLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(ProfessorRegLayout.createSequentialGroup()
                .addGroup(ProfessorRegLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(ProfessorRegLayout.createSequentialGroup()
                        .addGap(219, 219, 219)
                        .addComponent(btnsprofessorreg))
                    .addGroup(ProfessorRegLayout.createSequentialGroup()
                        .addGap(89, 89, 89)
                        .addGroup(ProfessorRegLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel17, javax.swing.GroupLayout.PREFERRED_SIZE, 140, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(ProfessorRegLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                .addGroup(ProfessorRegLayout.createSequentialGroup()
                                    .addComponent(jLabel22, javax.swing.GroupLayout.PREFERRED_SIZE, 140, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGap(98, 98, 98)
                                    .addComponent(txtsprofessorphone, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGroup(ProfessorRegLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addGroup(ProfessorRegLayout.createSequentialGroup()
                                        .addGap(14, 14, 14)
                                        .addComponent(jLabel15, javax.swing.GroupLayout.PREFERRED_SIZE, 324, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(ProfessorRegLayout.createSequentialGroup()
                                        .addComponent(jLabel20)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addComponent(txtsprofessorusername, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(ProfessorRegLayout.createSequentialGroup()
                                        .addComponent(jLabel21, javax.swing.GroupLayout.PREFERRED_SIZE, 140, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(98, 98, 98)
                                        .addComponent(txtsprofessorpass))
                                    .addGroup(ProfessorRegLayout.createSequentialGroup()
                                        .addComponent(jLabel16, javax.swing.GroupLayout.PREFERRED_SIZE, 140, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(98, 98, 98)
                                        .addGroup(ProfessorRegLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(txtsprofessorname, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(txtsprofessorid, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE))))
                                .addGroup(ProfessorRegLayout.createSequentialGroup()
                                    .addComponent(jLabel23, javax.swing.GroupLayout.PREFERRED_SIZE, 140, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGap(98, 98, 98)
                                    .addComponent(txtsprofessoremail, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE))))))
                .addContainerGap(365, Short.MAX_VALUE))
        );
        ProfessorRegLayout.setVerticalGroup(
            ProfessorRegLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, ProfessorRegLayout.createSequentialGroup()
                .addGap(14, 14, 14)
                .addComponent(jLabel15, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(ProfessorRegLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(txtsprofessorid, javax.swing.GroupLayout.DEFAULT_SIZE, 28, Short.MAX_VALUE)
                    .addComponent(jLabel16, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(ProfessorRegLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(txtsprofessorname, javax.swing.GroupLayout.DEFAULT_SIZE, 28, Short.MAX_VALUE)
                    .addComponent(jLabel17, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(ProfessorRegLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(txtsprofessorphone, javax.swing.GroupLayout.DEFAULT_SIZE, 28, Short.MAX_VALUE)
                    .addComponent(jLabel22, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGroup(ProfessorRegLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(ProfessorRegLayout.createSequentialGroup()
                        .addGap(7, 7, 7)
                        .addComponent(txtsprofessoremail, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(ProfessorRegLayout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel23, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(ProfessorRegLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(txtsprofessorusername, javax.swing.GroupLayout.DEFAULT_SIZE, 28, Short.MAX_VALUE)
                    .addComponent(jLabel20, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(ProfessorRegLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(txtsprofessorpass, javax.swing.GroupLayout.DEFAULT_SIZE, 30, Short.MAX_VALUE)
                    .addComponent(jLabel21, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(49, 49, 49)
                .addComponent(btnsprofessorreg)
                .addContainerGap(44, Short.MAX_VALUE))
        );

        jPanel2.add(ProfessorReg, "card6");

        jLabel14.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel14.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel14.setText("Student Login");
        jLabel14.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);

        jLabel11.setText("USERNAME");

        txtstudentusername.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtstudentusernameActionPerformed(evt);
            }
        });

        jLabel12.setText("PASSWORD");

        txtstudentpass.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtstudentpassActionPerformed(evt);
            }
        });

        btnstudentlogin.setText("Login");
        btnstudentlogin.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnstudentloginActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout StudentloginLayout = new javax.swing.GroupLayout(Studentlogin);
        Studentlogin.setLayout(StudentloginLayout);
        StudentloginLayout.setHorizontalGroup(
            StudentloginLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(StudentloginLayout.createSequentialGroup()
                .addGroup(StudentloginLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(StudentloginLayout.createSequentialGroup()
                        .addGap(89, 89, 89)
                        .addGroup(StudentloginLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel11)
                            .addGroup(StudentloginLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                .addComponent(jLabel14, javax.swing.GroupLayout.PREFERRED_SIZE, 324, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGroup(StudentloginLayout.createSequentialGroup()
                                    .addComponent(jLabel12, javax.swing.GroupLayout.PREFERRED_SIZE, 140, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGap(98, 98, 98)
                                    .addGroup(StudentloginLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                        .addComponent(txtstudentusername)
                                        .addComponent(txtstudentpass, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE))))))
                    .addGroup(StudentloginLayout.createSequentialGroup()
                        .addGap(222, 222, 222)
                        .addComponent(btnstudentlogin)))
                .addContainerGap(365, Short.MAX_VALUE))
        );
        StudentloginLayout.setVerticalGroup(
            StudentloginLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, StudentloginLayout.createSequentialGroup()
                .addGap(73, 73, 73)
                .addComponent(jLabel14, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(40, 40, 40)
                .addGroup(StudentloginLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel11)
                    .addComponent(txtstudentusername, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(StudentloginLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel12)
                    .addComponent(txtstudentpass, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(68, 68, 68)
                .addComponent(btnstudentlogin)
                .addContainerGap(89, Short.MAX_VALUE))
        );

        jPanel2.add(Studentlogin, "card6");

        btnProflogin.setText("Login");
        btnProflogin.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnProfloginActionPerformed(evt);
            }
        });

        btnProfregister.setText("Register");
        btnProfregister.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnProfregisterActionPerformed(evt);
            }
        });

        jLabel19.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel19.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel19.setText("Professor");
        jLabel19.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);

        javax.swing.GroupLayout ProflogregLayout = new javax.swing.GroupLayout(Proflogreg);
        Proflogreg.setLayout(ProflogregLayout);
        ProflogregLayout.setHorizontalGroup(
            ProflogregLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(ProflogregLayout.createSequentialGroup()
                .addGroup(ProflogregLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(ProflogregLayout.createSequentialGroup()
                        .addGap(302, 302, 302)
                        .addComponent(btnProflogin)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btnProfregister))
                    .addGroup(ProflogregLayout.createSequentialGroup()
                        .addGap(219, 219, 219)
                        .addComponent(jLabel19, javax.swing.GroupLayout.PREFERRED_SIZE, 324, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(249, Short.MAX_VALUE))
        );
        ProflogregLayout.setVerticalGroup(
            ProflogregLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(ProflogregLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel19, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(129, 129, 129)
                .addGroup(ProflogregLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnProflogin)
                    .addComponent(btnProfregister))
                .addContainerGap(191, Short.MAX_VALUE))
        );

        jPanel2.add(Proflogreg, "card5");

        jLabel24.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel24.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel24.setText("Admin Dasboard");
        jLabel24.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);

        btncreateProf.setText("Create Professor");
        btncreateProf.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btncreateProfActionPerformed(evt);
            }
        });

        btncreateStd.setText("Create Student");
        btncreateStd.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btncreateStdActionPerformed(evt);
            }
        });

        btncreateEmp.setText("Create Employer");
        btncreateEmp.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btncreateEmpActionPerformed(evt);
            }
        });

        btnviewProf.setText("View Professor");
        btnviewProf.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnviewProfActionPerformed(evt);
            }
        });

        btnviewStd.setText("View Student");
        btnviewStd.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnviewStdActionPerformed(evt);
            }
        });

        btncviewEmp.setText("View Employer");
        btncviewEmp.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btncviewEmpActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout AdmindasboradLayout = new javax.swing.GroupLayout(Admindasborad);
        Admindasborad.setLayout(AdmindasboradLayout);
        AdmindasboradLayout.setHorizontalGroup(
            AdmindasboradLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(AdmindasboradLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel24, javax.swing.GroupLayout.PREFERRED_SIZE, 324, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(164, 164, 164))
            .addGroup(AdmindasboradLayout.createSequentialGroup()
                .addGap(280, 280, 280)
                .addGroup(AdmindasboradLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(btncreateEmp, javax.swing.GroupLayout.PREFERRED_SIZE, 140, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btncreateProf, javax.swing.GroupLayout.PREFERRED_SIZE, 140, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btncreateStd, javax.swing.GroupLayout.PREFERRED_SIZE, 140, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(69, 69, 69)
                .addGroup(AdmindasboradLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(btncviewEmp, javax.swing.GroupLayout.PREFERRED_SIZE, 140, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnviewStd, javax.swing.GroupLayout.PREFERRED_SIZE, 140, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnviewProf, javax.swing.GroupLayout.PREFERRED_SIZE, 140, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(163, Short.MAX_VALUE))
        );
        AdmindasboradLayout.setVerticalGroup(
            AdmindasboradLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(AdmindasboradLayout.createSequentialGroup()
                .addGap(17, 17, 17)
                .addComponent(jLabel24, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(40, 40, 40)
                .addGroup(AdmindasboradLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(AdmindasboradLayout.createSequentialGroup()
                        .addComponent(btncreateProf, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(btncreateStd, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(btncreateEmp, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(AdmindasboradLayout.createSequentialGroup()
                        .addComponent(btnviewProf, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(btnviewStd, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(btncviewEmp, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(160, Short.MAX_VALUE))
        );

        jPanel2.add(Admindasborad, "card9");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnstduentActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnstduentActionPerformed
       // jPanel2.remove(EmptyPanel);
        jPanel2.removeAll();
        jPanel2.add(Stdlogreg);
        jPanel2.revalidate();
        jPanel2.repaint();
        //jPanel1.remove(StudentRegLogPanel);
        // TODO add your handling code here:
    }//GEN-LAST:event_btnstduentActionPerformed

    private void btnprofActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnprofActionPerformed
        jPanel2.removeAll();
       //jPanel2.remove(EmptyPanel);
        jPanel2.add(Proflogreg);
        jPanel2.revalidate();
        jPanel2.repaint();        // TODO add your handling code here:
    }//GEN-LAST:event_btnprofActionPerformed

    private void btnprofloginActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnprofloginActionPerformed

        String usernamelogin = txtprofusername.getText();
        String passwordlogin = txtprofpass.getText();        
        Encryptor encryptor = new Encryptor();
        String password=null;
        try {
            password = encryptor.encryptString(passwordlogin);
        } catch (NoSuchAlgorithmException ex) {
            Logger.getLogger(MainJFrame.class.getName()).log(Level.SEVERE, null, ex);
        }
        
//        System.out.println(usernamelogin);
//        System.out.println(password);
        if (database.containsKey(usernamelogin)) {
            
            if (database.containsValue(password)) {
//                LoginAsUserJPanel.setVisible(true);
//                MainScreenJPanel.setVisible(false);
                JOptionPane.showMessageDialog(this, "Logged in successfully!");
                profpanel = new Professor_JPanel(coursedetails,professor,courseSpringdetails);
 
                //studentpanel = new Student_JPanel(transcript, coursedetails,studentregisterdetails, course, studentRecord,courseSpringdetails,studentSpringdetails);
   // CourseHistory coursedetails;
//   CourseHistory coursedetails;
//    Professor professor;
//    Course course;
//    CourseHistory courseSpringdetails;
    //     (Transcript transcript, CourseHistory coursedetails, StudentCourse studentregisterdetails, Course course, StudentRecord studentRecord, CourseHistory courseSpringdetails, StudentCourse studentSpringdetails)
         jPanel2.removeAll();


            jPanel2.add(profpanel, "professor_jpanel");
            jPanel2.revalidate();
            jPanel2.repaint();


            }
            else{
                JOptionPane.showMessageDialog(this, "Invalid password for " +txtprofusername.getText() );
            }
        }
        else {
            JOptionPane.showMessageDialog(this, "Invalid username or password");
        }




        // TODO add your handling code here:
    }//GEN-LAST:event_btnprofloginActionPerformed

    private void btnregstdActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnregstdActionPerformed
 // TODO add your handling code here:
        String stdusername = txtstdusername.getText();
        String stdpassword = txtstdpass.getText();
        String name = txtstdname.getText();
        String stdaddr = txtstdaddr.getText();
        String stdemail = txtstdemail.getText();
        int stid = Integer.parseInt(txtstdid.getText());
        int stdphone = Integer.parseInt(txtstdphone.getText());
        Student st = stdrecord.addNewStudent();
        st.setStd_username(stdusername);
        st.setStd_password(stdpassword);
        st.setStd_name(name);
        st.setStd_addr(stdaddr);
        st.setStd_phone(stdphone);
        st.setStd_email(stdemail);
        st.setStd_id(stid);

       JOptionPane.showMessageDialog(this, "New User Added.");
      // TODO add your handling code here:
        String username = txtstdusername.getText();
        String input = txtstdpass.getText();
        String password = null;
        Encryptor encryptor = new Encryptor();
        
        try {
            System.out.println(encryptor.encryptString(input));
            password = encryptor.encryptString(input);

        } catch (NoSuchAlgorithmException ex) {
            Logger.getLogger(MainJFrame.class.getName()).log(Level.SEVERE, null, ex);
        }
       
        
        if (!username.isEmpty() && !password.isEmpty()) {   
            database.put(username, password);
            JOptionPane.showMessageDialog(this, "Credentials saved successfully!");
            txtstdusername.setText("");
            txtstdpass.setText("");
        } else {
            JOptionPane.showMessageDialog(this, "Please enter both username and password.");
        }
        for(int i=0;i<database.size();i++){
            System.out.println(database);
        }

        // TODO add your handling code here:
        
//        private int std_id;
//    private String std_name;
//    private String std_addr;
//    private int std_phone;
//    private String std_email;
//    private String std_username;
//    private String std_password;
//txtstdaddr;
//    private javax.swing.JTextField txtstdemail;
//    private javax.swing.JTextField txtstdid;
//    private javax.swing.JTextField txtstdname;
//    private javax.swing.JPasswordField txtstdpass;
//    private javax.swing.JTextField txtstdphone;
//    private javax.swing.JTextField txtstdusername;
//    private javax.swing.JPasswordField txtstudentpass;
//    private javax.swing.JTextField txtstudentusername;
    }//GEN-LAST:event_btnregstdActionPerformed

    private void btnStdloginActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnStdloginActionPerformed
        //jPanel2.remove(EmptyPanel);
        jPanel2.removeAll();
        jPanel2.add(Studentlogin);
        jPanel2.revalidate();
        jPanel2.repaint();
        // TODO add your handling code here:
    }//GEN-LAST:event_btnStdloginActionPerformed

    private void btnStdregisterActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnStdregisterActionPerformed
        jPanel2.removeAll();
        jPanel2.add(StudentReg);
        jPanel2.revalidate();
        jPanel2.repaint();
        // TODO add your handling code here:        // TODO add your handling code here:
    }//GEN-LAST:event_btnStdregisterActionPerformed

    private void btnstudentloginActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnstudentloginActionPerformed
        String usernamelogin = txtstudentusername.getText();
        String passwordlogin = txtstudentpass.getText();        
        Encryptor encryptor = new Encryptor();
        String password=null;
        try {
            password = encryptor.encryptString(passwordlogin);
        } catch (NoSuchAlgorithmException ex) {
            Logger.getLogger(MainJFrame.class.getName()).log(Level.SEVERE, null, ex);
        }
        
//        System.out.println(usernamelogin);
//        System.out.println(password);
        if (database.containsKey(usernamelogin)) {
            
            if (database.containsValue(password)) {
//                LoginAsUserJPanel.setVisible(true);
//                MainScreenJPanel.setVisible(false);
                JOptionPane.showMessageDialog(this, "Logged in successfully!");
            //Student_JPanel check = new Student_JPanel();
//            jPanel2.removeAll();
//            jPanel2.add( studentpanel);
    //     studentpanel = new Student_JPanel(coursedetails, studentregisterdetails,studentSpringdetails, course, studentRecord,courseSpringdetails,transcript);
         studentpanel = new Student_JPanel(transcript, coursedetails,studentregisterdetails, course, studentRecord,courseSpringdetails,studentSpringdetails);
   // CourseHistory coursedetails;

    //     (Transcript transcript, CourseHistory coursedetails, StudentCourse studentregisterdetails, Course course, StudentRecord studentRecord, CourseHistory courseSpringdetails, StudentCourse studentSpringdetails)
         jPanel2.removeAll();


            jPanel2.add(studentpanel, "studentPanel");
            jPanel2.revalidate();
            jPanel2.repaint();
      //      ((java.awt.CardLayout) studentpanel.getLayout()).next(studentpanel);
            }
            else{
                JOptionPane.showMessageDialog(this, "Invalid password for + " +txtstudentusername.getText() );
            }
        }
        else {
            JOptionPane.showMessageDialog(this, "Invalid username or password");
        }
        // TODO add your handling code here:
    }//GEN-LAST:event_btnstudentloginActionPerformed

    private void btnsprofessorregActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnsprofessorregActionPerformed
        String profusername = txtsprofessorusername.getText();
        String profpassword = txtsprofessorpass.getText();
        String name = txtsprofessorname.getText();
        String profemail = txtsprofessoremail.getText();
        int professorid = Integer.parseInt(txtsprofessorid.getText());
        int profphone = Integer.parseInt(txtsprofessorphone.getText());
        Professor pf = profrecord.addProfessor();
        pf.setProf_username(profusername);
        pf.setProf_password(profpassword);
        pf.setProfessorName(name);
        pf.setContactNo(profphone);
        pf.setEmail(profemail);
        pf.setProfessorID(professorid);

       JOptionPane.showMessageDialog(this, "New User Added.");
      // TODO add your handling code here:
        String username = txtsprofessorusername.getText();
        String input = txtsprofessorpass.getText();
        String password = null;
        Encryptor encryptor = new Encryptor();
        
        try {
            System.out.println(encryptor.encryptString(input));
            password = encryptor.encryptString(input);

        } catch (NoSuchAlgorithmException ex) {
            Logger.getLogger(MainJFrame.class.getName()).log(Level.SEVERE, null, ex);
        }
       
        
        if (!username.isEmpty() && !password.isEmpty()) {   
            database.put(username, password);
            JOptionPane.showMessageDialog(this, "Credentials saved successfully!");
            txtsprofessorusername.setText("");
            txtsprofessorpass.setText("");
        } else {
            JOptionPane.showMessageDialog(this, "Please enter both username and password.");
        }
        for(int i=0;i<database.size();i++){
            System.out.println(database);
        }





        // TODO add your handling code here:
    }//GEN-LAST:event_btnsprofessorregActionPerformed

    private void btnProfloginActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnProfloginActionPerformed
      jPanel2.removeAll();
   //     jPanel2.remove(Stdlogreg);
        jPanel2.add(ProfessorLog);
        jPanel2.revalidate();
        jPanel2.repaint();        // TODO add your handling code here:
    }//GEN-LAST:event_btnProfloginActionPerformed

    private void btnProfregisterActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnProfregisterActionPerformed
        // TODO add your handling code here:
              jPanel2.removeAll();
   //     jPanel2.remove(Stdlogreg);
        jPanel2.add(ProfessorReg);
        jPanel2.revalidate();
        jPanel2.repaint();   
    }//GEN-LAST:event_btnProfregisterActionPerformed

    private void txtstudentusernameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtstudentusernameActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtstudentusernameActionPerformed

    private void txtstdusernameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtstdusernameActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtstdusernameActionPerformed

    private void txtstudentpassActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtstudentpassActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtstudentpassActionPerformed

    private void txtstdpassActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtstdpassActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtstdpassActionPerformed

    private void btncreateProfActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btncreateProfActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btncreateProfActionPerformed

    private void btncreateStdActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btncreateStdActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btncreateStdActionPerformed

    private void btncreateEmpActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btncreateEmpActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btncreateEmpActionPerformed

    private void btnviewProfActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnviewProfActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnviewProfActionPerformed

    private void btnviewStdActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnviewStdActionPerformed
        jPanel2.removeAll();
   //   jPanel2.remove(Stdlogreg);
       // jPanel2.add(jPanel3);
        
        jPanel2.revalidate();
        jPanel2.repaint();   


        // TODO add your handling code here:
    }//GEN-LAST:event_btnviewStdActionPerformed

    private void btncviewEmpActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btncviewEmpActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btncviewEmpActionPerformed

    private void btnadminActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnadminActionPerformed
    adminPanel = new AdminJPanel(transcript, gettranscript);
     //   Iseligible.setEnabled(true);
        jPanel2.removeAll();
   //   jPanel2.remove(Stdlogreg);
        jPanel2.add(adminPanel);
        
        jPanel2.revalidate();
        jPanel2.repaint();   


        // TODO add your handling code here:
    }//GEN-LAST:event_btnadminActionPerformed

    private void btnempActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnempActionPerformed
    empPanel = new EmployeeJPanel(course, courseSpringdetails, coursedetails);

     jPanel2.removeAll();
   //   jPanel2.remove(Stdlogreg);
        jPanel2.add(empPanel);
        
        jPanel2.revalidate();
        jPanel2.repaint(); 
        // TODO add your handling code here:
    }//GEN-LAST:event_btnempActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(MainJFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(MainJFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(MainJFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(MainJFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new MainJFrame().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel Admindasborad;
    private javax.swing.JPanel EmptyPanel;
    private javax.swing.JPanel ProfessorLog;
    private javax.swing.JPanel ProfessorReg;
    private javax.swing.JPanel Proflogreg;
    private javax.swing.JPanel Stdlogreg;
    private javax.swing.JPanel StudentReg;
    private javax.swing.JPanel Studentlogin;
    private javax.swing.JButton btnProflogin;
    private javax.swing.JButton btnProfregister;
    private javax.swing.JButton btnStdlogin;
    private javax.swing.JButton btnStdregister;
    private javax.swing.JButton btnadmin;
    private javax.swing.JButton btncreateEmp;
    private javax.swing.JButton btncreateProf;
    private javax.swing.JButton btncreateStd;
    private javax.swing.JButton btncviewEmp;
    private javax.swing.JButton btnemp;
    private javax.swing.JButton btnprof;
    private javax.swing.JButton btnproflogin;
    private javax.swing.JButton btnregstd;
    private javax.swing.JButton btnsprofessorreg;
    private javax.swing.JButton btnstduent;
    private javax.swing.JButton btnstudentlogin;
    private javax.swing.JButton btnviewProf;
    private javax.swing.JButton btnviewStd;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel20;
    private javax.swing.JLabel jLabel21;
    private javax.swing.JLabel jLabel22;
    private javax.swing.JLabel jLabel23;
    private javax.swing.JLabel jLabel24;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPasswordField txtprofpass;
    private javax.swing.JTextField txtprofusername;
    private javax.swing.JTextField txtsprofessoremail;
    private javax.swing.JTextField txtsprofessorid;
    private javax.swing.JTextField txtsprofessorname;
    private javax.swing.JPasswordField txtsprofessorpass;
    private javax.swing.JTextField txtsprofessorphone;
    private javax.swing.JTextField txtsprofessorusername;
    private javax.swing.JTextField txtstdaddr;
    private javax.swing.JTextField txtstdemail;
    private javax.swing.JTextField txtstdid;
    private javax.swing.JTextField txtstdname;
    private javax.swing.JPasswordField txtstdpass;
    private javax.swing.JTextField txtstdphone;
    private javax.swing.JTextField txtstdusername;
    private javax.swing.JPasswordField txtstudentpass;
    private javax.swing.JTextField txtstudentusername;
    // End of variables declaration//GEN-END:variables
}
